Right workspaces?

diff --git a/src/Jenkinsfile_optA b/src/Jenkinsfile_optA
--- a/src/Jenkinsfile_optA
+++ b/src/Jenkinsfile_optA
@@ -8,48 +8,52 @@ checkout scm
                     """
                 }
                 
-        stage('Upload and Deploy') { // Stage umbenannt, da sie jetzt auch die Bereitstellung umfasst
-                echo 'Uploading application to IEM and deploying on device...'
-                sh """
-                    set -e # Beende das Skript sofort, wenn ein Befehl fehlschlägt
+                stage('Upload to IEM and deploy on Device') {
+                    sh """
+                    # A flag for bash scripts to exit on error
+                    set -e
 
- 
-                    rm -rf iectl_workspace
-                    mkdir iectl_workspace
-                    cp -RT app ./iectl_workspace
-                    cd iectl_workspace
-
-                    # 2. iectl Publisher konfigurieren
-                    # Wir verwenden 'localhost:2375' für den Docker-Daemon, da die Images lokal auf dem Agenten gebaut wurden.
-                    # '--workspace "."': iectl soll im aktuellen Verzeichnis nach den Projektdateien suchen.
-                    iectl config add publisher --name "publisher-local" --dockerurl "http://localhost:2375" --workspace "."
-
-                    # 3. IEM-Login konfigurieren
+                    #set envireonment variables for iectl
                     export IE_SKIP_CERTIFICATE=true
                     export EDGE_SKIP_TLS=1
+
+                    echo "----- Prepare workspace ------"
+                    rm -rf workspace
+                    mkdir workspace
+                    cd workspace
+
+                    echo "----- Set publisher configuration ------"
+                    iectl config add publisher --name "publisherdev" --dockerurl "http://docker:2375" --workspace "."
+
+                    iectl publisher workspace init
+                    cd ..
+                    cp -RT app ./workspace
+                    cd workspace
+
+                    echo "----- IEM Login ------"
                     iectl config add iem --name 'iemdev' --url "${IEM_URL}" --user "${USER_NAME}" --password "${PSWD}"
 
-                    # 4. Neue Anwendungsversion im IEM erstellen
-                    # Dieser Befehl lädt die Anwendung (inkl. der referenzierten Docker-Images vom lokalen Daemon) ins IEM hoch.
-                    iectl publisher app-project version create \\
-                        -a "${APP_ID}" \\
-                        -v "0.0.${BUILD_NUMBER}" \\
-                        -y ./docker-compose.prod.yml \\
-                        -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' \\
-                        -s 'hello-edge' \\
-                        -t 'FromBoxReverseProxy' \\
-                        -u 'hello-edge' \\
+                    echo "----- Create new app version ------"
+                    # I have used BUILD_NUMBER from Jenkins to create versions. If the apps are being deployed differentley as well you would need to get the version via "app-details"
+                    # This line can be used as an example to get last app version: OLD_VERSION=$(iectl iem app-project app-details --project-name "XXX" --app-name "XXX" | jq -r '.versions[0].versionNumber // "0.0.0"') 
+                    iectl publisher app-project version create \
+                        -a "${APP_ID}" \
+                        -v "0.0.${BUILD_NUMBER}" \
+                        -y ./docker-compose.prod.yml \
+                        -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' \
+                        -s 'hello-edge' \
+                        -t 'FromBoxReverseProxy' \
+                        -u 'hello-edge' \
                         -r '/'
 
-                    # 5. Anwendungsversion auf dem Edge-Gerät bereitstellen
-                    # Dieser Schritt ersetzt den 'uuv'-Befehl aus der ursprünglichen Methode A und entspricht der Bereitstellungslogik von Methode B.
-                    iectl iem app-project install \\
-                        -a "${APP_NAME}" \\
-                        --version "0.0.${BUILD_NUMBER}" \\
+                    echo "----- Deploy on edge device ------"
+                    iectl iem app-project install \
+                        -a "${APP_NAME}" \
+                        --version "0.0.${BUILD_NUMBER}" \
                         -i '{"devices":["'"${EDGE_DEVICE_ID}"'"]}'
-                """
-            
-        }
+                    """
+                }
+
                 stage('Cleanup Docker') {
                     sh """
                     docker ps -a | grep docker:24-dind | awk \'{print \$1}\' | xargs -r docker rm -f
