rework with IECTL

diff --git a/src/Jenkinsfile.txt b/src/Jenkinsfile.txt
--- a/src/Jenkinsfile.txt
+++ b/src/Jenkinsfile.txt
@@ -36,6 +36,7 @@ node {
                     """
                 }
                 // Push the image to the registry
+                /*
                 stage ('Upload') {
                      sh """
                         export DOCKER_HOST=tcp://docker:2375
@@ -54,14 +55,72 @@ node {
                         # Upload the app
                         ie-app-publisher-linux em app cuv -a $APP_ID -v 0.0.$BUILD_NUMBER -y ./docker-compose.prod.yml -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' -s 'hello-edge' -t 'FromBoxReverseProxy' -u "hello-edge" -r "/"
                         ie-app-publisher-linux em app uuv -a $APP_ID -v 0.0.$BUILD_NUMBER
-
+                     """
+                }*/
+                        /*
                         #Deploy the app on specific device
                         ie-app-publisher-linux em app install \
                         -n CICDTestMkII \
                         -v 0.0.$BUILD_NUMBER \
                         -d $EDGE_DEVICE_ID
-                     """
+                        */
+
+                        //The current version of ie-app-publisher-linux does not app deployment in its CLI
+
+                stage('Upload to IEM and deploy on Device') {
+                    sh """
+                        set -e
+
+                        echo "----- Prepare IE CLI Environment ------"
+                        export IE_SKIP_CERTIFICATE=true
+                        export EDGE_SKIP_TLS=1
+
+                        # Cleanup old workspace and start fresh
+                        rm -rf workspace
+                        mkdir workspace
+
+                        echo "----- Configure Docker Publisher ------"
+                        iectl config add publisher --name "publisherdev" --dockerurl "http://127.0.0.1:2375" --workspace "./workspace"
+
+                        echo "----- Initialize Publisher Workspace ------"
+                        iectl publisher workspace init
+
+                        echo "----- Configure IEM Connection ------"
+                        iectl config add iem --name "iemdev" --url "$IEM_URL" --user "$USER_NAME" --password "$PSWD"
+
+                        echo "----- Determine new version ------"
+                        OLD_VERSION=$(iectl iem app-project app-details --project-name "$APP_ID" --app-name "$APP_ID" | jq -r '.versions[0].versionNumber // "0.0.0"')
+                        IFS='.' read -r -a version_parts <<< "$OLD_VERSION"
+                        version_parts[2]=$((version_parts[2] + 1 ))
+                        NEW_VERSION="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
+                        export NEW_VERSION
+
+                        echo "Building version: $NEW_VERSION for app: $APP_ID"
+
+                        echo "----- Add new app version ------"
+                        iectl publisher app-project version create \
+                            -a "$APP_ID" \
+                            -v "$NEW_VERSION" \
+                            -y ./app/docker-compose.prod.yml \
+                            -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' \
+                            -s 'hello-edge' \
+                            -t 'FromBoxReverseProxy' \
+                            -u 'hello-edge' \
+                            -r '/'
+
+                        echo "----- Upload new app version ------"
+                        iectl publisher app-project version upload -a "$APP_ID" -v "$NEW_VERSION"
+
+                        echo "----- Deploy app to Edge Device ------"
+                        iectl iem app-project install \
+                            -a "$APP_ID" \
+                            --version "$NEW_VERSION" \
+                            -i '{"devices":["'"$EDGE_DEVICE_ID"'"]}'
+
+                        echo "----- DONE! ------"    
+                    """
                 }
+
                 /* Deploy the image to the edge device
                 stage('Deploy to Device') {
                     script {
