Tests for iem login

diff --git a/src/Jenkinsfile.txt b/src/Jenkinsfile.txt
--- a/src/Jenkinsfile.txt
+++ b/src/Jenkinsfile.txt
@@ -86,15 +86,20 @@ stage('Upload to IEM and deploy on Device') {
 
 
       # More debugging output
-      ls -l ./docker-compose.prod.yml
-      cat ./docker-compose.prod.yml
-      pwd
+      #ls -l ./docker-compose.prod.yml
+      #cat ./docker-compose.prod.yml
+      #pwd
 
       # Publisher-Konfiguration setzen (WICHTIG!)
       iectl config add publisher --name "publisher-dind" --dockerurl tcp://docker:2375 --workspace /app/src/workspace
       
       # Optional: Debug-Ausgabe
-      iectl config list publisher
+      #iectl config list publisher
+
+
+      # Debug for login failing
+      ping -c 3 192.168.56.4 || true
+      curl -vk https://192.168.56.4:443 || true
 
 
 
@@ -103,6 +108,15 @@ stage('Upload to IEM and deploy on Device') {
       export IE_SKIP_CERTIFICATE=true
       export EDGE_SKIP_TLS=1
       iectl config add iem --name "iemdev" --url "$IEM_URL" --user "$USER_NAME" --password "$PSWD"
+
+
+
+
+
+
+
+
+
       
       echo "----- Create new app version ------"
       iectl publisher app-project version create \
