Changed indetations

diff --git a/src/Jenkinsfile_optA b/src/Jenkinsfile_optA
--- a/src/Jenkinsfile_optA
+++ b/src/Jenkinsfile_optA
@@ -1,64 +1,70 @@
 node {
 checkout scm
     withEnv(['HOME=.']) {          
-                stage ('Build') {
-                    sh """
-                        cd src/app
-                        docker-compose build
-                    """
-                }
+        stage ('Build') {
+            sh """
+                cd src/app
+                docker-compose build
+                """
+            }
                 
-                stage('Upload to IEM and deploy on Device') {
-                    sh '''
-                    # A flag for bash scripts to exit on error
-                    set -e
+        stage('Upload to IEM and deploy on Device') {
+            sh '''
+                # A flag for bash scripts to exit on error
+                set -e
 
-                    echo "----- Set publisher configuration ------"
-                    iectl config add publisher --name "publisher" --dockerurl "http://docker:2375" --workspace "./workspace"
+                echo "--------------- Set publisher configuration ----------------"
+                iectl config add publisher --name "publisher" --dockerurl "http://docker:2375" --workspace "./workspace"
 
-                    echo "----- Prepare workspace ------"
-                    iectl publisher workspace init
+                echo "---------------- Prepare workspace -----------------"
+                iectl publisher workspace init
 
-                    echo "----- IEM Login ------"
-                    export IE_SKIP_CERTIFICATE=true
-                    export EDGE_SKIP_TLS=1
+                echo "---------------- IEM Login -----------------"
+                export IE_SKIP_CERTIFICATE=true
+                export EDGE_SKIP_TLS=1
 
-                    iectl config add iem \
-                        --name 'iemdev' \
-                        --url "${IEM_URL}" \
-                        --user "${USER_NAME}" \
-                        --password "${PSWD}"
+                iectl config add iem \
+                    --name 'iemdev' \
+                    --url "${IEM_URL}" \
+                    --user "${USER_NAME}" \
+                    --password "${PSWD}"
 
-                    echo "----- Create new app version ------"
-                    # I have used BUILD_NUMBER from Jenkins to create versions. If the apps are being deployed differentley as well you would need to get the version via "app-details"
-                    # This line can be used as an example to get last app version: OLD_VERSION=$(iectl iem app-project app-details --project-name "XXX" --app-name "XXX" | jq -r '.versions[0].versionNumber // "0.0.0"') 
-                    iectl publisher app-project version create \
-                        -a "${APP_ID}" \
-                        -v "0.0.${BUILD_NUMBER}" \
-                        -y "./src/app/docker-compose.prod.yml" \
-                        -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' \
-                        -s 'hello-edge' \
-                        -t 'FromBoxReverseProxy' \
-                        -u 'hello-edge' \
-                        -r '/'
+                echo "---------------- Create new app version -----------------"
+                # I have used BUILD_NUMBER from Jenkins to create versions. If the apps are being deployed differentley as well you would need to get the version via "app-details"
+                # This line can be used as an example to get last app version: OLD_VERSION=$(iectl iem app-project app-details --project-name "XXX" --app-name "XXX" | jq -r '.versions[0].versionNumber // "0.0.0"') 
+                iectl publisher app-project version create \
+                    -a "${APP_ID}" \
+                    -v "0.0.${BUILD_NUMBER}" \
+                    -y "./src/app/docker-compose.prod.yml" \
+                    -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' \
+                    -s 'hello-edge' \
+                    -t 'FromBoxReverseProxy' \
+                    -u 'hello-edge' \
+                    -r '/'
 
-                    echo "----- Deploy on edge device ------"
-                    iectl iem app-project install \
-                        -a "${APP_NAME}" \
-                        --version "0.0.${BUILD_NUMBER}" \
-                        -i '{"devices":["'"${EDGE_DEVICE_ID}"'"]}'
+                echo "---------------- Deploy on edge device -----------------"
+                iectl iem app-project install \
+                    -a "${APP_NAME}" \
+                    --version "0.0.${BUILD_NUMBER}" \
+                    -i '{"devices":["'"${EDGE_DEVICE_ID}"'"]}'
 
-                    #echo "----- Delete Specific App Versions ------"
-                    #iectl iem app-project version delete --app-id "${APP_ID}" --version-number "0.0.${BUILD_NUMBER}"
-                    '''
-                }
+                echo "---------------- Delete Specific App Versions -----------------"
+                iectl iem app-project version delete \
+                    --app-id "${APP_ID}" \
+                    --version-number \
+                    --"0.0.212"
+                    #--"0.0.${BUILD_NUMBER}" 
+                
+                '''
+        }
 
-                stage('Cleanup Docker') {
-                    sh """
-                    docker ps -a | grep docker:24-dind | awk \'{print \$1}\' | xargs -r docker rm -f
-                    docker system prune -af || true
-                    docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi || true
-                    """
-                }
+        stage('Cleanup Docker') {
+            sh """
+                docker ps -a | grep docker:24-dind | awk \'{print \$1}\' | xargs -r docker rm -f
+                docker system prune -af || true
+                docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi || true
+                
+                """
+        }
     }        
  }
